### ISSUE TITLE
Feature: Prepopulate URL from browser tabs

### ISSUE THREAD

**Issue by DynamicsNinja** [GuidoPreite/DRB_BrowserExtension#1]
It would be nice if the default value for the environment URL is pulled from the currently opened tabs:

  1. Prepopulated text field with the first one found
  2. Additional dropdown with all environments that are opened

**Comment by GuidoPreite** [comment]
A list of the environments is on the pipeline (dropdown or an expanded list of the most recent environments used).
Prepopulating the text by checking the other tabs is technically possible (as the extension uses the "tabs" permission) but is something I don't plan to add (the "tabs" permission is required to access the callback url but I don't want to use it for other scopes).
The code inside the main DRB repository has been also updated (as it is used by Dataverse DevTools) but I don't know if I will release 1.0.0.40 as Managed Solution and for XrmToolBox (because there are no changes for these two platforms) and go directly to 1.0.0.41 for all the platforms.

**Comment by GuidoPreite** [comment]
The latest version (1.0.0.41) contains a recent Environment URLs dropdown. It will keep track of the environment URLs inserted with the ability to delete them.
